name: Build and Test JNIDemo on ARM64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # 使用 Ubuntu 22.04 作为基础运行环境

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install ARM64 cross-compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu openjdk-17-jdk

    - name: Verify JDK installation
      run: |
        ls -la /usr/lib/jvm/java-17-openjdk/include
        ls -la /usr/lib/jvm/java-17-openjdk/include/linux
      

    - name: Build JNI project for ARM64
      run: |
        mkdir -p build && cd build
        cmake .. -DCMAKE_SYSTEM_NAME=Linux \
                 -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
                 -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
                 -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
                 -DJAVA_AWT_INCLUDE_PATH=/usr/lib/jvm/java-17-openjdk-arm64/include \
                 -DJAVA_AWT_LIBRARY=/usr/lib/jvm/java-17-openjdk-arm64/lib \
                 -DJAVA_JVM_LIBRARY=/usr/lib/jvm/java-17-openjdk-arm64/lib/server \
                 -DJAVA_INCLUDE_PATH=/usr/lib/jvm/java-17-openjdk-arm64/include \
                 -DJAVA_INCLUDE_PATH2=/usr/lib/jvm/java-17-openjdk-arm64/include/linux
        make

    - name: Verify Build Output
      run: ls -la build
