name: Build and Test JNIDemo on ARM64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # 使用 Ubuntu 22.04 作为基础镜像

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Test in ARM64 Docker Container
      run: |
        # 使用 ARM64 Docker 容器进行构建和测试
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace arm64v8/ubuntu:22.04 bash -c "
          apt-get update && \
          apt-get install -y cmake gcc g++ openjdk-17-jdk && \
          mkdir -p build && cd build && \
          cmake -DCMAKE_SYSTEM_NAME=Linux \
                -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
                -DCMAKE_C_COMPILER=gcc \
                -DCMAKE_CXX_COMPILER=g++ \
                .. && \
          make && \
          javac JNIDemo.java && \
          java -Djava.library.path=build JNIDemo
        "

    - name: Verify Output
      run: |
        ls -la build
